config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'how-it-works', to: 'home#how_it_works'
  get 'documentation', to: 'home#documentation'

  get 'apps', to: 'apps#index'
  get 'apps/new', to: 'apps#new'

  get 'check-verification-status', to: "application#reload"

  post 'signin', to: 'application#signin'
  get 'signout', to: 'application#signout'

  get 'api/:api_version/verify', to: 'apis#verification'
  get 'api/:api_version/cancel-sign-in', to: 'apis#sign_in_cancellation'

  post 'api/:api_version/authenticate', to: 'apis#authenticate_user'

  root 'home#index'

end

app/models/app.rb
class App < ApplicationRecord
    has_many :clients, dependent: :destroy
    belongs_to :user

    def icon_url
      "default_app_icon"
    end

    def alt_text
      "#{name} App Icon"
    end

    def new_client_with_language_code(language_code)
      clients.create(
        language_code: (language_code ? language_code : "en_US"),
        verification_token: SecureRandom.hex,
        verified: false
      )
    end

    def is_rejected
      false
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :app

  def expired
    created_at < 1.hour.ago
  end

  def token_matches(token)
    verification_token == token
  end

  def verify
    update_attributes(verification_token: nil, verified: true)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :apps
  validates :email_normalized, uniqueness: true
  validates :email_normalized, format: { with: URI::MailTo::EMAIL_REGEXP }

  def can_sign_into_app(app)
    app.user_access_list.split(' ').each do |user|
      if email_normalized == user || username_normalized == user
        return true
      elsif user.start_with? '*'
        return email_normalized.split("@")[1] == user.split("@")[1]
      end
    end
    false
  end
end

app/controllers/apis_controller.rb
require "#{Rails.root}/app/utils/database"

class ApisController < ApplicationController

  def sign_in_cancellation
    #different api versions possible: params[:api_version]
    client.destroy
  end

  def verification
    #different api versions possible: params[:api_version]
    client = Client.find_by_id(Integer(params[:client]))
    if !client.nil?
      if !client.expired && client.token_matches(params[:token])
        client.verify
        @app = App.find_by_name("Permissioner")
      else
        #validation failed: either link was too old or token doesn't match
        client.destroy
      end
    else
      render plain: "Client not found in database."
    end
  end

  def authenticate_user
    #different api versions possible: params[:api_version]
    error_message = nil
    permissioner_client_token = nil
    app = App.find_by_app_key(params[:app_key])
    if app.nil?
      error_message = "app_not_found"
    elsif app.is_rejected
      error_message = "app_status_rejected"
    else
      user = Database.new.fetchUser(params[:user])
      if user
        if user.can_sign_into_app(app)
          new_client = app.new_client_with_language_code(params[:language])
          payload = { iss: 'https://permissioner.com', client: new_client.id, user: user.id }
          permissioner_client_token = JsonWebToken.new.encode(payload)
          UserMailer.with(
            user: user,
            client: new_client,
            app: app
          ).verification_link_email.deliver_now
        else
          error_message = "user_access_denied"
        end
      else
        error_message = "invalid_user"
      end
    end

    json_response = {
      error: error_message,
      permissioner_client_token: permissioner_client_token
    }
    render json: json_response
  end

end

app/controllers/application_controller.rb
require 'securerandom'
require "#{Rails.root}/app/utils/database"
require "#{Rails.root}/app/utils/json_web_token"

class ApplicationController < ActionController::Base

  protect_from_forgery

  def reload
    redirect_back(fallback_location: root_path)
  end

  def signin
    user = Database.new.fetchUser(params[:username])
    permissioner = App.find_by_name('Permissioner')
    if user.nil?
      #TODO: let user know that user couldn't be found in database by username
      render plain: "The username doesn't exist in our database"
    elsif user.can_sign_into_app(permissioner)
      set_jwt_cookie(user)
      UserMailer.with(
        user: user,
        client: client,
        app: permissioner
      ).verification_link_email.deliver_now
      redirect_back(fallback_location: root_path)
    else
      #TODO: let user know that he is not allowed to sign into permissioner
      render plain: "You are not allowed to sign into Permissioner. Contact n.autzen@gmail.com to request access."
    end
  end

  def signout
    cookies.delete :jwt
    redirect_back(fallback_location: root_path)
  end


  def user
    jwt = cookies[:jwt]
    if jwt
      decoded_token = JsonWebToken.new.decode(jwt)
      User.find_by_id(decoded_token["user"])
    end
  end

  def client
    jwt = cookies[:jwt]
    if jwt
      decoded_token = JsonWebToken.new.decode(jwt)
      Client.find_by_id(decoded_token["client"])
    end
  end

  def set_jwt_cookie(user)
    jwt = new_jwt(user)
    cookies[:jwt] = {
      :value => jwt,
      :expires => 10.year.from_now,
      :httponly => true
    }
  end

  def new_jwt(user)
    client = new_client
    payload = { iss: 'https://permissioner.com', client: client.id, user: user.id }
    JsonWebToken.new.encode(payload)
  end

  def new_client
    App.find_by_name('Permissioner').clients.create(
      language_code: 'en_US',
      verification_token: SecureRandom.hex,
      verified: false
    )
  end

  def is_client_verified
    client.nil? ? false : client.verified
  end

end

app/controllers/apps_controller.rb
class AppsController < ApplicationController

  def index
    @is_client_verified = is_client_verified
    if !@is_client_verified
      redirect_to root_path
    else
      @user = user
      @apps = App.where(user_id: @user.id)
    end
  end

  def new
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = user
    @is_client_verified = is_client_verified
  end

  def how_it_works
    @user = user
    @is_client_verified = is_client_verified
  end

  def documentation
    @user = user
    @is_client_verified = is_client_verified
  end
  
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/apis/sign_in_cancellation.html.erb
<p>You successfully cancelled your sign in attempt.</p>
<p>You can close this window.</p>

app/views/apis/verification.html.erb
<div id="wrapper">
    <% if @app %>
      <%= image_tag(@app.icon_url, alt: @app.alt_text) %>
      <h2><%= @app.name %></h2>
      <p>You successfully verified your email address.</p>
      <p>Close this window and return to where you signed in from.</p>
    <% else %>
      <p>Verification failed! You probably waited too long to click on the link we sent you.</p>
      <p>Go back where you're trying to sign in from and try it again.</p>
    <% end %>
</div>

app/views/apps/index.html.erb
<%= render 'home/menu_header', user: @user, is_client_verified: @is_client_verified, show_signin_sheet: true %>

<h1>Apps</h1>
<ul>
  <% @apps.each do |app| %>
    <li><%= app.name %>: <%= app.app_key %></li>
  <% end %>
</ul>

app/views/apps/new.html.erb
<h1>New App</h1>

app/views/home/_benefits.html.erb
<a name="benefits"></a>
      <div id="benefits">
        <h2>Benefits of using Permissioner to authenticate your users</h2>
        <ul>
          <li>
            <h3>No password management</h3>
            <p>Free yourself from the burden of securly managing passwords. No salting, hashing, storing, resetting and changing of passwords necessary.</p>
          </li>
          <li>
            <h3>No passwords to steal</h3>
            <p>You don't need a password database at all. That means, you never have to worry about being the target of a hacker trying to steal your users passwords. You simultaniously render password phishing attacks impossible, protecting your users in the process.</p>
          </li>
          <li>
            <h3>Easy to integrate</h3>
            <p>It just takes a few simple steps. See the <%= link_to 'Documentation', documentation_path %> to learn how to do it. If you want to replace the conventional user authentication process in an existing app / website, you additionally have to remove everything password related, like your password database and the password field in your Sign In interface.</p>
          </li>
          <li>
            <h3>Simplified Sign Up / Sign In</h3>
            <p>You don't need an extra sign up process for new users: if a user signs in, he / she automatically has to verify his / her email address.</p>
          </li>
          <li>
            <h3>Get more users to try your app / website</h3>
            <p>Many users feel hesitant to sign up for an unknown app / website just to try it out. Most users will reuse one of their few, easy to remember passwords when they sign up for a new service. Giving another app / website access to one of these passwords makes many users feel uneasy and maybe even prevent them from using it at all. Therefore, you might get more users to try out your app / website, if they don't have to enter a password.</p>
          </li>
          <li>
            <h3>Advanced user access control</h3>
            <p>Every app / website you add to Permissioner comes with build in access control. You can either allow anyone to sign in by default, but block specific users (Blacklist), or block everyone by default and only grant access to some (Whitelist). Permissioner also supports wildcard email addresses (e. g. *yourcompany.com). This way you are able to restrict access to only your employees.</p>
          </li>
          <li>
            <h3>It's free</h3>
            <p>Using Permissioner to authenticate your users is and will forever be free.</p>
          </li>
        </ul>
      </div>

app/views/home/_faq.html.erb
<a name="faqs"></a>
      <div id="faqs">
          <h2>FAQs</h2>
          <ul>
            <li>
              <h3>Do my users need a Permissioner account in order to sign into my app?</h3>
              <p>No. All Permissioner needs to authenticate a user is his / her email address, which your app / website provides during the authentication process.</p>
            </li>
            <li>
              <h3>How secure is it? What if a user's email account gets hacked?</h3>
              <p>Permissioner is more secure than the classic password based authentication process. It uses pretty much the same mechanics, but replaces weak user generated passwords with secure, randomly generated keys. The <%= link_to 'How It Works', how_it_works_path %> page explains it in more detail.</p>
              <p>If a user's email account would be hacked, the attacker could sign into your app / website pretending to be this particular user. But the same is also true for the password based authentication. A hacker who has access to the user's email account, could simply reset the user's password and gain access to his / her account this way.</p>
            </li>
            <li>
              <h3>What are the benefits of using Permissioner over Sign In with Google, Facebook, Twitter & Co?</h3>
              <p>Not every user will have one of the accounts your app / website could support. In order not to exclude any users, you would still need to offer the password based sign in mechanics, with all its drawbacks. The costs of implementing multiple sign in alternatives would most definitely exceed the costs of integrating Permissioner. Furthermore, many users feel uncomfortable giving another service access to their Facebook / Google / Twitter account.</p>
            </li>
          </ul>
      </div>
    </div>

app/views/home/_how_to.html.erb
<a name="how-to"></a>
      <div id="how_to_use_it">
        <h2>How to let your users sign in with Permissioner</h2>
        <%= image_tag("how-it-works.png", alt: "How Permissioner's user authentication works") %>
        <ol>
          <li>You integrate Permissioner into your app or website.</li>
          <li>Your users sign in, using only their email addresses.</li>
          <li>Permissioner takes care of the authentication process.</li>
          <li>Permissioner tells you if the user signed in successfully.</li>
        </ol>
        <p>See <%= link_to 'How it works', how_it_works_path %> for a more detailed and technical explanation. See the <%= link_to 'Documentation', documentation_path %> for a complete guide on how to integrate Permissioner into your app / website.</p>
      </div>

app/views/home/_login_form.html.erb
<%= form_tag("signin", method: "post") do %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
 <%= text_field_tag :username, nil, placeholder: 'Email / Username' %>
 <%= submit_tag 'Sign up / in' %>
<% end %>

app/views/home/_menu_header.html.erb
<div id="menu">
  <nav>
    <ul>
        <li><%= link_to 'Home ', root_path %></li>
        <li><%= link_to 'How It Works ', how_it_works_path %></li>
        <li><%= link_to 'Documentation (API)', documentation_path %></li>
    </ul>
  </nav>
  <% if show_signin_sheet %>
    <% if @user.nil? || !@user.email %>
      <%= render 'login_form' %>
    <% elsif !@is_client_verified %>
        <div>
          You're trying to sign in as <i><%= @user.username ? @user.username : @user.email_normalized %></i> We've sent you a link. <%= link_to 'Cancel Sign in', signout_path %> <%= link_to 'I verified myself', check_verification_status_path %>
        </div>
    <% else %>
      <div>
        n.autzen@gmail.com <%= link_to 'Your Apps', apps_path %> <%= link_to 'Sign out', signout_path %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/home/how_it_works.html.erb
<%= render 'menu_header', user: @user, is_client_verified: @is_client_verified, show_signin_sheet: true %>

        <div id="wrapper">
          <h1>How does authenticating users in your app / website with Permissioner work?</h1>
          <p>Permissioner's process to authenticate users for other apps / websites is quite simple. In addition to the following technical explanation, make sure to read the <%= link_to 'Documentation', documentation_path %> to understand how to use it.</p>

          <a name="authentication"></a>
          <h2>Authentication process</h2>
            <ol>
              <%= image_tag("authentication_request.png", alt: "Authentication Request Icon") %>
              <li>When you want to authenticate a user, your app / website has to send the <%= link_to '/autenticate', documentation_path(anchor: 'api') %> request to Permissioner's API, containing your app's / website's App Key and the user's email address.</li>
              <%= image_tag("app_user_verification.png", alt: "App and user verification icon") %>
              <li>Permissioner then identifies your app / website via the App Key and validates that it is allowed to use Permissioner and that the provided email address is allowed to sign into it.</li>
              <li>If both holds true, Permissioner generates an anonymized <i>clientID</i>, representing the client the user is trying to sign into. With the clientID, it is possible for Permissioner to distinctly assign an authentication attempt to a specific client.</li>
              <li>With the clientID, Permissioner generates a secure verification link. It then sends this link to the user's email address in form of a verification request on your app's / website's behalf. The verification link is only valid for an hour.</li>
              <%= image_tag("sending_email_verification.png", alt: "Sending email verification link icon") %>
              <%= image_tag("authentication_response.png", alt: "Authentication Request Icon") %>
              <li>With the user's email address and the newly created clientID, Permissioner also generates the <i>permissioner_client_token</i> - a JSON Web Token (JWT) that is needed for the next API request. Inside the API response, this token is then send back to your app / website, where you need to store it in order to later check, if the user verified his / her email address with Permissioner.</li>
            </ol>

            <a name="verification"></a>
            <h2>Email address verification</h2>
            <ol>
              <%= image_tag("email_verification.png", alt: "User verifies his/her email address icon") %>
              <li>To verify his / her email address and complete the sign in process, the user needs to click on the verification link sent to him / her. By doing so, Permissioner is ensured that the user has indeed access to the provided email address, which it then can attest to your app / website.</li>
              <%= image_tag("verification_status.png", alt: "Check Verification Status Icon") %>
              <li>To check if the user has verified his / her email address, your app / website needs to send the <%= link_to '/verificationStatus', documentation_path(anchor: 'api') %> request to Permissioner's API. If the API response tells you, that the user did verify it, you can grant him / her access to the underlying account in which the user is trying to sign into.</li>
            </ol>
        </div>

app/views/home/index.html.erb
<%= render 'menu_header', user: @user, is_client_verified: @is_client_verified, show_signin_sheet: @is_client_verified %>
<div id="wrapper">
  <header>
      <h1>Permissioner</h1>
      <h4>for Developers</h4>
      <h2>secure, passwordless authentication for your users</h2>
      <% if !@user || !@user.email %>
        <%= render 'login_form' %>
      <% elsif !@is_client_verified %>
        <p>You're trying to sign in as <%= @user.username ? @user.username : @user.email_normalized %>. Verify yourself, by clicking on the link we sent you.<br /><br />Don't want to sign in?  <%= link_to 'Cancel Sign in', signout_path %></p>
        <p><%= link_to 'I Verified Myself', check_verification_status_path %></p>
      <% end %>
  </header>
  <%= render 'benefits' %>
  <%= render 'how_to' %>
  <%= render 'faq' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>